# Generated by Django 4.0.2 on 2022-08-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, height_field=200, upload_to='taxi', width_field=300),
            preserve_default=False,
        ),
    ]
