# Generated by Django 4.0.2 on 2022-08-20 22:24

from django.db import migrations, models
import taxi.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_alter_car_image_alter_manufacturer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to=taxi.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, upload_to=taxi.models.path_and_rename),
        ),
    ]
